/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacegrafica;

import bo.ChaleBO;
import ctrl.ChaleCTRL;
import java.text.ParseException;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author ManaimTI
 */
public class ManterChale extends javax.swing.JInternalFrame {

    /**
     * Creates new form ManterChale
     */
    public ManterChale() {
        initComponents();
        BloquearCampos();
        bt_salvar.setEnabled(false);
        bt_editar.setEnabled(false);
        txt_codChale.setEditable(true);
    }
    
    ChaleBO chaleBo = new ChaleBO();
    ChaleCTRL chaleCtrl = new ChaleCTRL();
    String op = "";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_codChale = new javax.swing.JTextField();
        txt_descChale = new javax.swing.JTextField();
        bt_novo = new javax.swing.JButton();
        bt_salvar = new javax.swing.JButton();
        bt_buscar = new javax.swing.JButton();
        bt_editar = new javax.swing.JButton();
        bt_fechar = new javax.swing.JButton();

        setTitle("Cadastro de Chalés");

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Chalés"));

        jLabel1.setText("Código Chalé: ");

        jLabel2.setText("Desc Chalé: ");

        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txt_codChale, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txt_descChale, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(txt_codChale, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txt_descChale))
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_codChale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txt_descChale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        bt_novo.setText("Novo");
        bt_novo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_novo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_novoActionPerformed(evt);
            }
        });

        bt_salvar.setText("Salvar");
        bt_salvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_salvar.setVerifyInputWhenFocusTarget(false);
        bt_salvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salvarActionPerformed(evt);
            }
        });

        bt_buscar.setText("Buscar");
        bt_buscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_buscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_buscarActionPerformed(evt);
            }
        });

        bt_editar.setText("Editar");
        bt_editar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_editar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_editarActionPerformed(evt);
            }
        });

        bt_fechar.setText("Fechar");
        bt_fechar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_fechar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_fecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_buscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_fechar)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_novo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_salvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_fechar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_editar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_novoActionPerformed
        op = "incluir";
        txt_codChale.setEnabled(false);
        txt_codChale.setText(String.valueOf(chaleBo.getCod_chale()+ 1)); //TESTE DE ALTO INCREMENTO DO PROX CODIGO
        DesbloquearCampos();
        //LimparCampos();
        bt_novo.setEnabled(false);
        bt_buscar.setEnabled(false);
        bt_editar.setEnabled(false);
        bt_salvar.setEnabled(true);
    }//GEN-LAST:event_bt_novoActionPerformed

    private void bt_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salvarActionPerformed
        if (!txt_descChale.getText().equals("")) {

            try {
                chaleBo.setDesc_chale(txt_descChale.getText());                

                if ("incluir".equals(op)) {
                    chaleCtrl.IncluirChale(chaleBo);
                }

                if ("alterar".equals(op)) {
                    chaleCtrl.AlterarChale(chaleBo);
                }

                JOptionPane.showMessageDialog(null, "Salvo com sucesso.");
                op = "";
                LimparCampos();
                DesbloquearCampos();
                txt_codChale.setEnabled(true);
                bt_editar.setEnabled(false);
                bt_salvar.setEnabled(false);
                bt_buscar.setEnabled(true);
                bt_novo.setEnabled(true);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "O nome, tipo e CPF/CNPJ são obrigatórios.");
        }
    }//GEN-LAST:event_bt_salvarActionPerformed

    private void bt_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_buscarActionPerformed
        ChaleBO retorno = new ChaleBO();
        try {
            chaleBo.setCod_chale(Integer.parseInt(txt_codChale.getText()));
            retorno = chaleCtrl.BuscaChale(chaleBo);

            txt_descChale.setText(retorno.getDesc_chale());
            
            bt_editar.setEnabled(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Chalé não encontrado.");
            LimparCampos();
        }
    }//GEN-LAST:event_bt_buscarActionPerformed

    private void bt_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editarActionPerformed
        op = "alterar";
        bt_buscar.setEnabled(false);
        bt_salvar.setEnabled(true);
        bt_novo.setEnabled(false);
        bt_editar.setEnabled(false);
        DesbloquearCampos();
        txt_codChale.setEditable(false);
    }//GEN-LAST:event_bt_editarActionPerformed

    private void bt_fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_fecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_bt_fecharActionPerformed

    private void LimparCampos() {
        txt_codChale.setText("");
        txt_descChale.setText("");
        
    }

    private void BloquearCampos() {
        txt_codChale.setEditable(false);
        txt_descChale.setEditable(false);
        
    }

    private void DesbloquearCampos() {
        txt_codChale.setEditable(true);
        txt_descChale.setEditable(true);
        ;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_buscar;
    private javax.swing.JButton bt_editar;
    private javax.swing.JButton bt_fechar;
    private javax.swing.JButton bt_novo;
    private javax.swing.JButton bt_salvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JTextField txt_codChale;
    private javax.swing.JTextField txt_descChale;
    // End of variables declaration//GEN-END:variables
}
