/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacegrafica;

import bo.LocarChaleBO;
import ctrl.LocarChaleCTRL;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class ManterLocacao extends javax.swing.JInternalFrame {
    private Util u = new Util();

    private JFrame tela1;

    /**
     * Creates new form ManterLocacao
     */
    public ManterLocacao() {
        initComponents();
        this.tela1 = tela1;
    }

    LocarChaleBO locarchaleBo = new LocarChaleBO();
    LocarChaleCTRL locarchaleCtrl = new LocarChaleCTRL();
    String op = "";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        bt_ListarSocio = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_matriculaSocio = new javax.swing.JTextField();
        txt_nomeSocio = new javax.swing.JTextField();
        bt_novo = new javax.swing.JButton();
        bt_salvar = new javax.swing.JButton();
        bt_buscar = new javax.swing.JButton();
        bt_editar = new javax.swing.JButton();
        bt_fechar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_NumLocacao = new javax.swing.JTextField();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        bt_listarChale = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_codChale = new javax.swing.JTextField();
        txt_descChale = new javax.swing.JTextField();

        setTitle("Locação");

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Sócio"));

        bt_ListarSocio.setText("Listar");
        bt_ListarSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ListarSocioActionPerformed(evt);
            }
        });

        jLabel1.setText("Matricula:");

        jLabel2.setText("Nome: ");

        jLayeredPane1.setLayer(bt_ListarSocio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txt_matriculaSocio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txt_nomeSocio, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_ListarSocio)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(txt_matriculaSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txt_nomeSocio))))
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_ListarSocio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_matriculaSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_nomeSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        bt_novo.setText("Novo");
        bt_novo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_novo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_novoActionPerformed(evt);
            }
        });

        bt_salvar.setText("Salvar");
        bt_salvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_salvar.setVerifyInputWhenFocusTarget(false);
        bt_salvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salvarActionPerformed(evt);
            }
        });

        bt_buscar.setText("Buscar");
        bt_buscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_buscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_buscarActionPerformed(evt);
            }
        });

        bt_editar.setText("Editar");
        bt_editar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_editar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_editarActionPerformed(evt);
            }
        });

        bt_fechar.setText("Fechar");
        bt_fechar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_fechar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_fecharActionPerformed(evt);
            }
        });

        jLabel3.setText("Num Locação:");

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Chalé"));

        bt_listarChale.setText("Listar");
        bt_listarChale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_listarChaleActionPerformed(evt);
            }
        });

        jLabel4.setText("Cód. Chalé:");

        jLabel5.setText("Desc. Chalé:");

        txt_codChale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codChaleActionPerformed(evt);
            }
        });

        jLayeredPane2.setLayer(bt_listarChale, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(txt_codChale, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(txt_descChale, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_descChale, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bt_listarChale)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_codChale, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_listarChale)
                .addGap(9, 9, 9)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_codChale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_descChale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_NumLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(bt_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_buscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_fechar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLayeredPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_novo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_salvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_fechar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_editar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_NumLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_novoActionPerformed
        op = "incluir";
        txt_NumLocacao.setEnabled(false);
        txt_NumLocacao.setText(String.valueOf(locarchaleBo.getNum_aluguel() + 1)); //TESTE DE ALTO INCREMENTO DO PROX CODIGO
        DesbloquearCampos();
        //LimparCampos();
        bt_novo.setEnabled(false);
        bt_buscar.setEnabled(false);
        bt_editar.setEnabled(false);
        bt_salvar.setEnabled(true);
    }//GEN-LAST:event_bt_novoActionPerformed

    private void bt_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salvarActionPerformed
        if ((!txt_matriculaSocio.getText().equals("")) || (!txt_codChale.getText().equals(""))) {

            try {
                locarchaleBo.setMatriculaSocio(Integer.parseInt(txt_matriculaSocio.getText()));
                locarchaleBo.setNum_chale(Integer.parseInt(txt_codChale.getText()));

                if ("incluir".equals(op)) {
                    locarchaleCtrl.IncluirLocacao(locarchaleBo);
                }

                if ("alterar".equals(op)) {
                    locarchaleCtrl.AlterarLocacao(locarchaleBo);
                }

                JOptionPane.showMessageDialog(null, "Salvo com sucesso.");
                op = "";
                LimparCampos();
                DesbloquearCampos();
                txt_NumLocacao.setEnabled(true);
                bt_editar.setEnabled(false);
                bt_salvar.setEnabled(false);
                bt_buscar.setEnabled(true);
                bt_novo.setEnabled(true);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "O Sócio e o chalé são obrigatórios.");
        }
    }//GEN-LAST:event_bt_salvarActionPerformed

    private void bt_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_buscarActionPerformed
        LocarChaleBO retorno = new LocarChaleBO();
        try {
            locarchaleBo.setNum_aluguel(Integer.parseInt(txt_NumLocacao.getText()));
            retorno = locarchaleCtrl.BuscaLocacao(locarchaleBo);

            txt_matriculaSocio.setText(toString());
            //txt_codChale.set(retorno.getTipo()); CORRIGIR
            // txt_documento.setText(retorno.getDocumento()); CORRIGIR

            bt_editar.setEnabled(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Locação não encontrado.");
            LimparCampos();
        }
    }//GEN-LAST:event_bt_buscarActionPerformed

    private void bt_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editarActionPerformed
        op = "alterar";
        bt_buscar.setEnabled(false);
        bt_salvar.setEnabled(true);
        bt_novo.setEnabled(false);
        bt_editar.setEnabled(false);
        DesbloquearCampos();
        txt_NumLocacao.setEditable(false);
    }//GEN-LAST:event_bt_editarActionPerformed

    private void bt_fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_fecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_bt_fecharActionPerformed

    private void txt_codChaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codChaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codChaleActionPerformed

    private void bt_ListarSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ListarSocioActionPerformed
        ListarSocio f1 = new ListarSocio();
        Principal.jDesktopPane1.add(f1);        
        f1.setVisible(true);
        Util u = null;
        this.u.centralizar(f1);
    }//GEN-LAST:event_bt_ListarSocioActionPerformed

    private void bt_listarChaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_listarChaleActionPerformed
        ListarChale f2 = new ListarChale();
        Principal.jDesktopPane1.add(f2);
        f2.setVisible(true);
        Util u = null;
        this.u.centralizar(f2);
    }//GEN-LAST:event_bt_listarChaleActionPerformed

    private void LimparCampos() {
        txt_NumLocacao.setText("");
        txt_matriculaSocio.setText("");
        txt_nomeSocio.setText("");
        txt_codChale.setText("");
        txt_descChale.setText("");
    }

    private void BloquearCampos() {
        txt_NumLocacao.setEditable(false);
        txt_matriculaSocio.setEditable(false);
        txt_nomeSocio.setEditable(false);
        txt_codChale.setEditable(false);
        txt_descChale.setEditable(false);

    }

    private void DesbloquearCampos() {
        txt_NumLocacao.setEditable(true);
        txt_matriculaSocio.setEditable(true);
        txt_nomeSocio.setEditable(true);
        txt_codChale.setEditable(true);
        txt_descChale.setEditable(true);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_ListarSocio;
    private javax.swing.JButton bt_buscar;
    private javax.swing.JButton bt_editar;
    private javax.swing.JButton bt_fechar;
    private javax.swing.JButton bt_listarChale;
    private javax.swing.JButton bt_novo;
    private javax.swing.JButton bt_salvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JTextField txt_NumLocacao;
    private javax.swing.JTextField txt_codChale;
    private javax.swing.JTextField txt_descChale;
    private javax.swing.JTextField txt_matriculaSocio;
    private javax.swing.JTextField txt_nomeSocio;
    // End of variables declaration//GEN-END:variables
}
